### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by steve-ico3** [globalpayments/php-sdk#107]
Hi all,

Trying to update to v4 but as I'm on php 8 it currently fails

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - globalpayments/php-sdk[4.0.0, ..., 4.0.5] require php ^7.1 -> your php version (8.1.8) does not satisfy that requirement.
```

Noticed there's a pull request from 27 days ago to patch this but it's still pending, does v4 not support php 8 or is it untested on 8 or something?

https://github.com/globalpayments/php-sdk/pull/105

**Comment by rxp-developers** [comment]
Hello,

Due to some breaking changes from PHP > 8.0 we update the composer to
support PHP version lower than 8. Those changes are work in progress at the
moment with a probable release date this month.


Kind regards,

*Cristina Nechita*
*Senior Developer*, Contractor

*Global Payments*
***@***.*** ***@***.***>


On Mon, Aug 8, 2022 at 4:32 PM 'Steve King' via DL_Developers <
***@***.***> wrote:

> Hi all,
>
> Trying to update to v4 but as I'm on php 8 it currently fails
>
> Your requirements could not be resolved to an installable set of packages.
>
>   Problem 1
>     - globalpayments/php-sdk[4.0.0, ..., 4.0.5] require php ^7.1 -> your php version (8.1.8) does not satisfy that requirement.
>
> Noticed there's a pull request from 27 days ago to patch this but it's
> still pending, does v4 not support php 8 or is it untested on 8 or
> something?
>
> #105
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_globalpayments_php-2Dsdk_pull_105&d=DwMCaQ&c=zQ6tLaF7dShu6emFdFLQLeh4ApIjUVDHmN_RmdGFa9g&r=QDDMxukUX4zqjTxKNXuNmzSFpuFZFz9Hs0l2FXcTpQA&m=45T_dvhhbcS6NFRZVXEGVrt9rLeUX2N4FY4PuX5pEsE37jXpWLQxnLRBEOzLqTL8&s=Q5WiPWIHpy_qES-S1aCwwBxv5L570zNmTfmmIvWzKD4&e=>
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_globalpayments_php-2Dsdk_issues_107&d=DwMCaQ&c=zQ6tLaF7dShu6emFdFLQLeh4ApIjUVDHmN_RmdGFa9g&r=QDDMxukUX4zqjTxKNXuNmzSFpuFZFz9Hs0l2FXcTpQA&m=45T_dvhhbcS6NFRZVXEGVrt9rLeUX2N4FY4PuX5pEsE37jXpWLQxnLRBEOzLqTL8&s=gB-Z4nciVM3HU-jSOvT-VSGzV6tvflN0TZPNjMNgOZc&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AG3Z63MFTILD3HX35ZETRILVYED5RANCNFSM555EXNCQ&d=DwMCaQ&c=zQ6tLaF7dShu6emFdFLQLeh4ApIjUVDHmN_RmdGFa9g&r=QDDMxukUX4zqjTxKNXuNmzSFpuFZFz9Hs0l2FXcTpQA&m=45T_dvhhbcS6NFRZVXEGVrt9rLeUX2N4FY4PuX5pEsE37jXpWLQxnLRBEOzLqTL8&s=2kZW4jN7shkt1UKpf07pnO7Vn3LhhFlFBH3lN_oYeTk&e=>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

-- 
NOTICE: This email message is for the sole use of the addressee(s) named 
above and may contain confidential and privileged information. Any 
unauthorized review, use, disclosure or distribution of this message or any 
attachments is expressly prohibited. If you are not the intended recipient, 
please contact the sender by reply email and destroy all copies and backups 
of the original message.
