### ISSUE TITLE
Bug: Syntax Error, Unexpected '?'

### ISSUE THREAD

**Issue by mike-brookes** [globalpayments/php-sdk#27]
PHP 5.6 Bug in: globalpayments/php-sdk/src/Gateways/Gp3DSProvider.php in multiple locations...

example:

$request['payer'] = $this->maybeSetKey($request['payer'], 'email', $builder->getCustomerEmail() ?? null);

Should be I guess :

$request['payer'] = $this->maybeSetKey($request['payer'], 'email', $builder->getCustomerEmail() ? $builder->getCustomerEmail() : null;

Unless this is no longer true:
Requirements: PHP 5.5.9+

PHP 7+ is required for ?? syntax to work.

**Comment by mike-brookes** [comment]
Unless this is no longer true: 
Requirements: PHP 5.5.9+

PHP 7+ is required for ?? syntax to work.

**Comment by swamp-dweller** [comment]
I also have this problem.  The suggested fix is not quite correct.  It should be:

$request['payer'] = **isset(** $this->maybeSetKey($request['payer'], 'email', $builder->getCustomerEmail() **)** ? $builder->getCustomerEmail() : null;

Or, more generally, all the statements of the form 
**$a = $b ?? $c;**
need to be converted to
**$a = isset( $b ) ? $b : $c;**
in order to work in PHP 5.6.
