### ISSUE TITLE
Populating browser data from browser?

### ISSUE THREAD

**Issue by craigcarnell** [globalpayments/php-sdk#29]
Hi,

Browser data - what is a required field for 3DS2 and what are optional?

How have you managed to pass this onto the web browser -> php?

Http user agent, accept headers and ip address are easy enough, but what about color depth, java, screen height, screen width, challenge window size?

Also, what format is language and timezone?

The following is taken from: vendor/globalpayments/php-sdk/test/Integration/Gateways/RealexConnector/Secure3dServiceTests.php
```
// browser data
        $this->browserData = new BrowserData();
        $this->browserData->acceptHeader = 'text/html,application/xhtml+xml,application/xml;q=9,image/webp,img/apng,*/*;q=0.8';
        $this->browserData->colorDepth = ColorDepth::TWENTY_FOUR_BITS;
        $this->browserData->ipAddress = '123.123.123.123';
        $this->browserData->javaEnabled = true;
        $this->browserData->language = 'en';
        $this->browserData->screenHeight = 1080;
        $this->browserData->screenWidth = 1920;
        $this->browserData->challengWindowSize = ChallengeWindowSize::WINDOWED_600X400;
        $this->browserData->timeZone = '0';
        $this->browserData->userAgent = 'Mozilla/5.0 (Windows NT 6.1; Win64, x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36';
```

**Comment by rxp-developers** [comment]
Hi Craig,

All the browser data is mandatory.

If you're using our JavaScript Library, it will gather the client-side browser data on your behalf: https://github.com/globalpayments/globalpayments-3ds-js

Otherwise you can use a combination of client-side and server-side methods to obtain it, please refer to: https://developer.globalpay.com/#!/api/3d-secure-two#3ds2-device

For more information on the required format (although the code samples should provide what you need) please refer to the Request Syntax table in https://developer.globalpay.com/#!/api/3d-secure-two#3ds2-initiate

**Comment by craigcarnell** [comment]
@rxp-developers thanks, will take a look :+1:
