### ISSUE TITLE
InitiateAutentication - Format of one or more Data Elements is Invalid according to the Specification - cardDetail.firstName

### ISSUE THREAD

**Issue by craigcarnell** [globalpayments/php-sdk#39]
It appears that banks are rejecting single letter first names and this is a problem.

For example, on my card form a customer can enter: T Test, or J Bloggs etc.

I am then setting the card holder name:

```
$card = new CreditCardData();
$card->cardHolderName = trim($cardHolderName)
```

This generates this XML:

```
"full_name":"t test","first_name":"t","last_name":"test"
```

But I get back the following error message:
```
"error_code" : "203",
  "error_component" : "S",
  "error_description" : "Format of one or more Data Elements is Invalid according to the Specification",
  "error_detail" : "cardDetail.firstName",
```

It appears when doing a check for SCA you cannot use a single character for the first name.

I have contacted realex and they have suggested only supplying full_name field instead, but the API supplies full_name, first_name and last_name

Can you offer a way of only setting full name if required and not giving first_name/last_name?

https://github.com/globalpayments/php-sdk/blob/1fd0393b3fc231fcff2977a152b7a7b9e0c1d57f/src/Gateways/Gp3DSProvider.php#L159

**Comment by slogsdon** [comment]
@craigcarnell Thanks for sending this over. We're working on a solution for this.

**Comment by seonzoo** [comment]
Hi @slogsdon is there any update on this?

We've had the same issue, there is no meaningful feedback in the response, and haven't had any luck with technical issues from customer support.

This is what we've been testing over the past few days:

https://donate-sca.zoo.fyi

**Comment by seonzoo** [comment]
Hello, I've since tested this again, and now we're just getting timeout errors

I have changed the card object so the keys are camelCase and correct, but still the timeouts are happening.

![Screen Shot 2020-02-17 at 18 11 13](https://user-images.githubusercontent.com/7262729/74750241-52a4e680-5263-11ea-9daa-510037b0b6c1.png)

**Comment by seonzoo** [comment]
Please ignore the previous post, I can't edit it - the timeouts were a  browser issue.

Anyway, thanks to craigcarnell, I was able to find a place to return the error_detail

I had to modify this block of code:
https://github.com/globalpayments/php-sdk/blob/master/src/Gateways/RestGateway.php#L39

It turns out that the expiry_year is expecting the format YYYY, and nullifying any 2-digit year. even though all the examples I have looked at show 2 digits.
https://github.com/globalpayments/php-sdk/blob/master/src/Gateways/Gp3DSProvider.php#L156

We now have the issue of state (as in city, state, country) being invalid, and not accepting empty values.
