### ISSUE TITLE
Declaration of GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig::configureContainer($services) must be compatible with GlobalPayments\Api\ServiceConfigs\Configuration::configureContainer(GlobalPayments\Api\ConfiguredServices $services)

### ISSUE THREAD

**Issue by izamzam2020** [globalpayments/php-sdk#62]
I'm following the guide here - https://developer.globalpay.com/ecommerce/3d-secure-version1#api using PHP (API) .

I have downloaded the package via composer to the version that's referenced (2.0.0) and when I run the code I get the following error.

Declaration of GlobalPayments\Api\ServiceConfigs\Gateways\GpEcomConfig::configureContainer($services) must be compatible with GlobalPayments\Api\ServiceConfigs\Configuration::configureContainer(GlobalPayments\Api\ConfiguredServices $services)

I have also tried using version 2.1.0

My server is running PHP 7

Thanks

**Comment by cifsl** [comment]
same problem here, we fixed with this patch on file Gateways\ServiceConfigs\Gateways\GpEcomConfig.php (https://github.com/globalpayments/php-sdk/blob/master/src/ServiceConfigs/Gateways/GpEcomConfig.php)

new namespace import reference

`
use GlobalPayments\Api\ConfiguredServices;
`

replaced $services param type on configureContainer method to match the abstract class

from

`
public function configureContainer($services) {
`

to

`
public function configureContainer(ConfiguredServices $services) {
`

can anyone from project owners add/fix this ?

**Comment by footfish** [comment]
FYI - I experienced this fault on PHP 5.5.9, PHP 7.0.33 but not PHP 7.2.24.

**Comment by izamzam2020** [comment]
Thanks Cifsl,

Your code fixed the first error which then created another error:

"Secure 3D is not connected to connector" - the following issue request has the fix for that if anyone else gets the same errors
